CREATE OR REPLACE TRIGGER TR_I_TIPO_ERRO
   BEFORE INSERT ON TIPO_ERRO
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
BEGIN
   :NEW.TIPOERRO_ID := TIPOERRO_SEQ.NEXTVAL;
END TR_I_TIPO_ERRO;
/
